services:

  db:
    hostname: db
    image: postgres:16
    volumes:
      - gophercises-ex7:/var/lib/postgresql/data

    restart: always
    environment:
      # Local env only
      POSTGRES_PASSWORD: test
      POSTGRES_DB: task_db

    ports:
      - "5432:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d task_db" ]
      interval: 5s
      timeout: 5s
      retries: 6
      start_period: 3s
      start_interval: 3s

volumes:
  gophercises-ex7: